CREATE TABLE EMP
(
empno INT,
ename VARCHAR(25),
job VARCHAR(12),
salary INT,
commission INT,
deptno INT
);
SELECT * FROM EMP;
DESCRIBE EMP;
INSERT INTO EMP(empno,ename,job,salary,deptno) VALUES(7369,'SMITH','CLERK',800,20);
SELECT * FROM EMP;
INSERT INTO EMP(empno,ename,job,salary,commission,deptno) VALUES(7499,'ALLEN','SALESMAN',1600,300,30),(7521,'WARD','SALESMAN',1250,500,30),(7654,'MARTIN','SALESMAN',1250,1400,30);
INSERT INTO EMP(empno,ename,job,salary,deptno) VALUES(7566,'JONES','MANAGER',2975,20),(7698 ,'BLAKE','MANAGER',2850,30),(7782,'CLARK','MANAGER',2450,10),(7788 ,'SCOTT','ANALYST',3000,20),(7839,'KING','PRESIDENT',5000,10),(7844,'TURNER','SALESMAN',1500,30),(7876,'ADAMS','CLERK',1100,20),(7900 ,'JAMES','NULL',950,30),(7902,'FORD','ANALYST',3000,20),(7934,'MILLER','CLERK',1300,10);
UPDATE EMP
SET job='CLERK'WHERE job='NULL';
SELECT * FROM EMP;
ALTER TABLE EMP
ADD COLUMN date_join varchar(50);
SELECT * FROM EMP;
UPDATE EMP 
SET date_join='17-DEC-80' WHERE empno='7369';
SELECT * FROM EMP;
UPDATE EMP 
SET date_join='20-FEB-81' WHERE empno='7499';
UPDATE EMP 
SET date_join='22-FEB-81' WHERE empno='7521';
UPDATE EMP 
SET date_join='02-APR-81' WHERE empno='7566';
UPDATE EMP 
SET date_join='28-SEP-81' WHERE empno='7654';
UPDATE EMP 
SET date_join='01-MAY-81' WHERE empno='7698';
UPDATE EMP 
SET date_join='09-JUN-81' WHERE empno='7782';
UPDATE EMP 
SET date_join='19-APR-87' WHERE empno='7788';
UPDATE EMP 
SET date_join='17-NOV-81' WHERE empno='7839';
UPDATE EMP 
SET date_join='08-SEP-81' WHERE empno='7844';
UPDATE EMP 
SET date_join='23-MAY-87' WHERE empno='7876';
UPDATE EMP 
SET date_join='03-DEC-81' WHERE empno='7900';
UPDATE EMP 
SET date_join='03-DEC-81' WHERE empno='7902';
UPDATE EMP 
SET date_join='23-JAN-82' WHERE empno='7934';
DESCRIBE EMP;
SELECT * FROM EMP;
SELECT DISTINCT job FROM EMP;
SELECT ename,deptno FROM EMP WHERE deptno IN (20,30);
SELECT ename,(salary + IFNULL(commission,0)) AS total_salary FROM EMP;
SELECT * FROM EMP;
SELECT ENAME,SALARY*12 AS ANNUAL_SALARY FROM EMP;
SELECT ENAME FROM EMP WHERE DATE_JOIN='03-DEC-81';
SELECT  (salary + IFNULL( commission,0)) AS total_salary FROM EMP WHERE ename='MILLER';
SELECT * FROM EMP;
DELETE FROM EMP WHERE ename='MILLER';
SELECT * FROM EMP;
SELECT ename, deptno FROM EMP;
SELECT * FROM EMP;
ALTER TABLE EMP ADD COLUMN total_salary numeric;
UPDATE EMP SET total_salary=(salary+ IFNULL(commission,0));
ALTER TABLE EMP DROP COLUMN commission;
SELECT*FROM EMP;
SELECT E.empno,E.salary FROM EMP E INNER JOIN EMP B ON E.salary AND E.empno<>B.empno;
DESCRIBE EMP;
SELECT ename AS name,empno AS emp_id FROM EMP;
RENAME TABLE EMP to EMPLOYEE;
DESCRIBE EMPLOYEE;
CREATE TABLE STUDENT
(
sid INT,
sname VARCHAR(25),
dob VARCHAR(12),
physics INT,
chemistry INT,
maths INT
);
DESCRIBE STUDENT;
INSERT INTO STUDENT(sid,sname,dob,physics,chemistry,maths) VALUES(1,'Dona','08-07-1999',80,88,86),(2,'sara','08-07-1997',60,75,86),(3,'bhagya','11-07-1994',20,81,20),(4,'aiden','21-11-1999',70,88,86),(5,'steve','09-08-1999',50,68,76);
SELECT * FROM STUDENT;
SELECT sid,sname FROM STUDENT  WHERE dob=(SELECT max(dob)from STUDENT);
SELECT * FROM STUDENT WHERE maths >=40 and (physics >=40 or chemistry >=40);
ALTER TABLE STUDENT ADD total int;
ALTER TABLE STUDENT ADD average float(10,3);
DESCRIBE STUDENT;
SELECT sname FROM STUDENT WHERE maths=(SELECT max(maths) FROM STUDENT);
SELECT sname FROM STUDENT WHERE chemistry=(SELECT min(chemistry) FROM STUDENT);
UPDATE STUDENT SET total=physics+chemistry+maths;
SELECT * FROM STUDENT;
UPDATE STUDENT SET average=total/3;
SELECT * FROM STUDENT;
SELECT * FROM STUDENT ORDER BY total DESC;
ALTER TABLE STUDENT RENAME COLUMN average TO avg_mark;
SELECT * FROM STUDENT;
SELECT *FROM STUDENT WHERE avg_mark > (SELECT AVG(avg_mark) FROM STUDENT);
SELECT COUNT(*) FROM STUDENT WHERE AVG_MARK > (SELECT AVG(AVG_MARK) FROM STUDENT);
CREATE TABLE LOAN_ACCOUNTS
(
ACCNO CHAR(4),
CUST_NAME VARCHAR(15),
LOAN_AMOUNT DECIMAL(10,2),
INSTALLMENT INT,
INT_RATE DECIMAL(10,2),
START_DATE DATE,
INTEREST DECIMAL(10,2)
);
DESCRIBE LOAN_ACCOUNTS;
DROP TABLE LOAN_ACCOUNTS;
ALTER TABLE LOAN_ACCOUNTS ADD COLUMN CATEGORY VARCHAR(10);
INSERT INTO LOAN_ACCOUNTS(ACCNO,CUST_NAME,LOAN_AMOUNT,INSTALLMENT,INT_RATE,START_DATE)VALUES(1001,'R.K GUPTA',300000.00,36,12.00,'2009-07-19'),
(1002,'S.P SHARMA',500000.00,48,10.00,'2008-03-22'),
(1003,'K.P JAIN',300000.00,36,NULL,'2007-08-03'),
(1004,'M.P YADAV',800000.00,60,10.00,'2008-06-12'),
(1005,'S.P SINHA',200000.00,36,12.50,'2010-03-01'),
(1006,'P SHARMA',700000.00,60,12.50,'2008-05-06'),
(1007,'K.S DHALL',500000.00,48,NULL,'2008-05-03');
SELECT * FROM LOAN_ACCOUNTS;
TRUNCATE TABLE LOAN_ACCOUNTS;
UPDATE LOAN_ACCOUNTS SET INT_RATE=11.50 WHERE INT_RATE IS NULL;
SELECT * FROM LOAN_ACCOUNTS;
UPDATE LOAN_ACCOUNTS SET INT_RATE=INT_RATE + 0.5 WHERE LOAN_AMOUNT> 400000;
SELECT * FROM LOAN_ACCOUNTS;
UPDATE LOAN_ACCOUNTS SET INTEREST=(LOAN_AMOUNT * INT_RATE * INSTALLMENT)/(12*100);
SELECT * FROM LOAN_ACCOUNTS;
DELETE  FROM LOAN_ACCOUNTS WHERE START_DATE < '2008-01-01';
SELECT * FROM LOAN_ACCOUNTS;
DELETE FROM LOAN_ACCOUNTS WHERE CUST_NAME like 'K%';
SELECT * FROM LOAN_ACCOUNTS WHERE INSTALLMENT < 40;
SELECT INT_RATE FROM LOAN_ACCOUNTS WHERE START_DATE > '2009-04-01';
SELECT ACCNO, CUST_NAME, LOAN_AMOUNT FROM LOAN_ACCOUNTS WHERE CUST_NAME like '%SHARMA';
SELECT  CUST_NAME,LOAN_AMOUNT FROM LOAN_ACCOUNTS WHERE CUST_NAME LIKE '%a';
SELECT ACCNO, CUST_NAME, LOAN_AMOUNT FROM LOAN_ACCOUNTS WHERE CUST_NAME LIKE '%a%';
SELECT ACCNO, CUST_NAME, LOAN_AMOUNT FROM LOAN_ACCOUNTS WHERE NOT(CUST_NAME LIKE '%P%');
DESCRIBE LOAN_ACCOUNTS;
SELECT * FROM LOAN_ACCOUNTS ORDER BY  LOAN_AMOUNT ASC;
SELECT * FROM LOAN_ACCOUNTS ORDER BY  START_DATE DESC;
SELECT * FROM LOAN_ACCOUNTS ORDER BY LOAN_AMOUNT, START_DATE DESC;
SELECT * FROM LOAN_ACCOUNTS WHERE CUST_NAME LIKE 'K%';
SELECT * FROM LOAN_ACCOUNTS WHERE INT_RATE IS NULL;
SELECT * FROM LOAN_ACCOUNTS WHERE INT_RATE is NOT NULL;
SELECT DISTINCT LOAN_AMOUNT FROM LOAN_ACCOUNTS ;
SELECT * FROM LOAN_ACCOUNTS WHERE START_DATE >'2008-12-31' AND  INSTALLMENT >36;
SELECT CUST_NAME,LOAN_AMOUNT FROM LOAN_ACCOUNTS WHERE LOAN_AMOUNT <500000 OR  INT_RATE >12;
SELECT * FROM LOAN_ACCOUNTS WHERE YEAR(START_DATE)='2009';
SELECT * FROM LOAN_ACCOUNTS WHERE LOAN_AMOUNT BETWEEN 400000 AND  500000;
SELECT CUST_NAME,LOAN_AMOUNT FROM LOAN_ACCOUNTS WHERE INSTALLMENT IN(26,36,48);
 SELECT CUST_NAME,LOAN_AMOUNT,INT_RATE,
 CASE WHEN INT_RATE  IS NULL THEN '0' ELSE INT_RATE END FROM LOAN_ACCOUNTS;
 SELECT CUST_NAME,LOAN_AMOUNT,INT_RATE,
 CASE WHEN INT_RATE  IS NULL THEN 'No Interest' ELSE INT_RATE END FROM LOAN_ACCOUNTS;